#
# Login file for SELI
# Do not edit this file, local settings should be put in .cshrc.user
#

if ( -r /etc/home/cshrc && -d /env ) then
	source /etc/home/cshrc
else
	if ( `uname -s` == "SunOS" && -f /usr/local/lib/Tcshrc ) then
	        source /usr/local/lib/Tcshrc
	endif

	if ( -f ${HOME}/.cshrc.user ) then
		source ${HOME}/.cshrc.user
	endif
endif
